# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source "https://codehub-dg-g.huawei.com/application_market_business/AppGalleryConnectSDK/AM_AppGallery_AppGalleryConnectSDK_ios_spec.git"

target 'AGConnectStorageDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "AGConnectStorage"
  pod "AGConnectAuth"

end

target 'AGConnectStorageDemo-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "AGConnectStorage"
  pod "AGConnectAuth"

end
